## The name of singer
spk: "oniku_kurumi"

## exp tag(for managing experiments)
tag:

## Directory of Unzipped singing voice database
# PLEASE CHANGE THE PATH BASED ON YOUR ENVIRONMENT
db_root: "../db/ONIKU_KURUMI_UTAGOE_DB"

## Output directory
# All the generated labels, intermediate files, and segmented wav files
# will be saved in the following directory
out_dir: "./data"

## Songs to be excluded from training.
exclude_songs: []

### Pyinsy related settings.
## Sinsy dictionary directory
# This singing voice database contains the unvoiced vowels "I" and "U".
# To enable the unvoiced vowels, modified version of sinsy dictionary files
# are needed.
sinsy_dic: "../3rdparty/nnsvs/recipes/_common/no2/dic"

### Data preparation related settings.
## Song segmentation by silence durations.
# TODO: would be better to split songs by phrasal information in the musical scores
# Split song by silences (in sec)
segmentation_threshold: 0.4
# Min duration for a segment
# note: there could be some exceptions (e.g., the last segment of a song)
segment_min_duration: 5.0
# Force split segments if long silence is found regardless of min_duration
force_split_threshold: 5.0
# Offset correction
# If True, offset is computed in an entire song
# otherwise offset is computed for each segment
global_offset_correction: False
offset_correction_threshold: 0.01
# Time-lag constraints to filter outliers
timelag_allowed_range: [-20, 19]
timelag_allowed_range_rest: [-40, 39]
# Audio sampling rate
# CAUTION: Changing sample_rate may affect the dimension number of acoustic features.
# DO NOT CHANGE this unless you know the relationship between the dim of bap and sample_rate.
sample_rate: 48000
